{ ... }:
{
  imports = [
    ./format.nix
    ./generate_toc.nix
    ./each.nix
    ./which_file.nix
    ./install-font.nix
    ./install-rpm.nix
    ./convert-file.nix
    ./fzf-rg-edit.nix
    ./fzf-preview.nix
    ./extract.nix
    ./select-and-open-video.nix
    ./telepush.nix
    ./scratch.nix
    ./nano_usage.nix
    ./sleep-cycles.nix
    ./copy-files.nix
    ./remove.nix
    ./compress-wrap.nix
    ./open.nix
    ./direnv-wrap.nix
    ./rclone-sync.nix
    ./ai-bridge.nix
    ./read.nix
    ./quick-aliases.nix
  ];
}
