{ ... }:
{
  imports = [
    ./bat.nix
    ./eza.nix
    ./fd.nix
    ./fzf.nix
    ./github.nix
    ./television.nix
    ./yazi.nix
    ./zoxide.nix
    ./java.nix
    ./direnv.nix
    ./fastfetch.nix
    ./git.nix
    ./tmux.nix
    ./helix
    ./nushell.nix
    ./agents
    ./yt-dlp.nix
    ./neovim.nix
    ./kitty.nix
    ./pinta.nix
    ./alacritty.nix
    ./qutebrowser.nix
    ./packages
    ./zed
    ./yt-dlp.nix
    ./obs.nix
    ./mcfly.nix
    ./9router.nix
    ./pandoc.nix
    ./neovide.nix
  ];
}
